### PR TITLE
Added Debug and Error Logs with Req ID, Latency

### PR DESCRIPTION
**Pull request by windkit**
## Description
Added Access Log, Updated Debug and Error Logs with Req ID, Latency

## Related Issue
https://github.com/leo-project/leofs/issues/493

### CODE REVIEW

**Comment by yosukehara** [comment]
@windkit Thanks. I've reviewed your PR. So I would like to ask you to improve the access-log's message because we want to deliver easily understanding with it.

- Current:
```erlang
?access_log_storage_get($KEY, $REQUEST_ID, $BEGIN_TIME, "error"),
```

- After:

```erlang
%% + $brief-error-message
?access_log_storage_get($KEY, $REQUEST_ID, $BEGIN_TIME, "error:$brief-error-message"),
```

**Comment by windkit** [comment]
I am now tidying up the log a bit more, please wait before

**Comment by windkit** [comment]
### Access Log
Method | Source  | Key | Size | Request ID | Time | Time stamp | Latency | Status
---------|----|----|----|----|----|---|---|---
[GET]|[Storage]|test/3030580|0||2016-12-06 13:19:48.773514 +0900|1480997988773545|0|error
[PUT]|[Storage]|test/450547|11358|25285068|2016-12-06 13:19:48.770263 +0900|1480997988770297|1|ok

### Error Log
```
-----+---------------------+---------------------------------------+----------------+-----------------------------------------------+-------+--------------------------------------------------------------------
Type |    Node             |                Time                   |   Time Stamp   |                Module:Function                |  Line |            Error Message
-----+---------------------+---------------------------------------+----------------+-----------------------------------------------+-------+--------------------------------------------------------------------
[E]     S1@192.168.100.37       2016-12-06 13:19:48.777420 +0900        1480997988      leo_storage_handler_object:[Gateway] get/3      135     [get] Key:<<"test/2542471">>, Req ID:46060231, Error:not_found
[E]     S1@192.168.100.37       2016-12-06 13:19:48.777662 +0900        1480997988      leo_storage_handler_object:[Gateway] get/3      135     [get] Key:<<"test/928818">>, Req ID:61416325, Error:not_found
```

### Info Log
```
-----+---------------------+---------------------------------------+----------------+-----------------------------------------------+-------+--------------------------------------------------------------------
Type |    Node             |                Time                   |   Time Stamp   |                Module:Function                |  Line |            Error Message
-----+---------------------+---------------------------------------+----------------+-----------------------------------------------+-------+--------------------------------------------------------------------
[D]     S1@192.168.100.37       2016-12-06 13:19:48.771350 +0900        1480997988      leo_storage_handler_object:[Gateway] get/3      124     [get] Key:<<"test/3432287">>, Req ID:31308650
[D]     S1@192.168.100.37       2016-12-06 13:19:48.771623 +0900        1480997988      leo_storage_handler_object:[Gateway] get/3      124     [get] Key:<<"test/928818">>, Req ID:61416325
```

**Comment by yosukehara** [comment]
@windkit I've checked your code. So I'd like to ask you to modify error-log output using [?error(_Func,_MsgL)](https://github.com/leo-project/leo_logger/blob/develop/include/leo_logger.hrl#L138-L144) as below:

```erlang
%% before
?error("[Storage] get/1", "[get] Key:~p, Error:~p", [Key, Cause]),

%% after
?error("get/1", [{from, storage}, {method, get} , {key, Key}, {cause, Error}]),
```

**Comment by windkit** [comment]
Now it is updated as
```
[E]     node_0@leofs-ubuntu1404-node01  2016-12-07 09:13:47.819545 +0900        1481069627      leo_storage_handler_object:get/1        84      [{from,storage},{method,get},{key,<<"air/on/g/string">>},{cause,not_found}]
```

**Comment by yosukehara** [comment]
@windkit Merged, thanks

**Pull request merged**
